apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: __PVC_NAME__
  namespace: __NAMESPACE__
  labels:
    app: __WORKER_NAME__
    app.kubernetes.io/name: __WORKER_NAME__
    app.kubernetes.io/component: local-goal-agent
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: __PVC_SIZE__
  storageClassName: local-path
